### ISSUE TITLE
半透明的背景，不能遮挡UIStatuBar。在UIStatusBarStyleLightContent这种状态

### ISSUE THREAD

**Issue by weiwei1035** [iTofu/LCActionSheet#1]
在appdelegate加入
[[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];
在plist文件中
View controller-based status bar appearance设置为NO
把ViewController的背景色设置为灰色。就看的很清楚

**Comment by iTofu** [comment]
谢谢！
