### ISSUE TITLE
Cancel button shows Chinese characters, can we modify the text of the cancel button?

### ISSUE THREAD

**Issue by BichengLUO** [iTofu/LCActionSheet#10]
I found that "Cancel" button is always attributed with Chinese characters. What if we want to implement an international solution using LCActionSheet? At the present, I implemented it in this way:

``` objc
- (NSString *)cancelText
{
    if (_cancelText) {
        return _cancelText;
    }

    _cancelText = NSLocalizedString(@"cancel", nil);
    return _cancelText;
}
```

Thus, I suppose that it's better to provide a function for modifying the text of cancel button.

**Comment by iTofu** [comment]
I see, thank you! But I'm a little busy now (Spring Festival is coming you know, and the company work...), you could submit a [PR](https://github.com/LeoiOS/LCActionSheet/pulls) to this project if you have time, thanks again :)

**Comment by BichengLUO** [comment]
Sorry, I finally found that the lib provided a property 'cancelText', it's plausible to modify the text of cancel button. It's no need to PR. Anyway, thank you for your patience.

The issue can be closed now.
