### ISSUE TITLE
关于默认“取消” 按钮的疑问？

### ISSUE THREAD

**Issue by mrhyh** [iTofu/LCActionSheet#12]
你好，你的项目写得非常棒，我也在用它。只是我有个疑问，你为什么把默认的“取消”按钮设置为黑色，或者说你为什么不把它的颜色设定也开放出来！

**Comment by iTofu** [comment]
谢谢。是这样，取消意味着不进行任何操作，也即保持原样。一般而言，保持原样不需要警示。

**Comment by mrhyh** [comment]
好的！thank you！
