### ISSUE TITLE
超出屏幕后不能滚动

### ISSUE THREAD

**Issue by jinweizhao** [iTofu/LCActionSheet#17]
希望bottomView可以换成scrollview或者在bottomView上再放一个scrollview。

**Comment by iTofu** [comment]
feature, TODO...

**Comment by iTofu** [comment]
你可以fork过去改一下

**Comment by iTofu** [comment]
@jinweizhao 
该需求已实现。详见 [V 2.0.0](https://github.com/iTofu/LCActionSheet/releases/tag/2.0.0)。
