### ISSUE TITLE
希望可以自定义高亮文字的颜色

### ISSUE THREAD

**Issue by IAMJ** [iTofu/LCActionSheet#18]
也就是 redBtn 的文字颜色

**Comment by iTofu** [comment]
请稍等。

**Comment by iTofu** [comment]
@IAMJ 
已支持该需求，发布于 [V 2.1.1](https://github.com/iTofu/LCActionSheet/releases/tag/2.1.1)，详见 [Demo Code](https://github.com/iTofu/LCActionSheet#代码-code)！

**Comment by IAMJ** [comment]
@iTofu 已更新验证
