### ISSUE TITLE
希望添加背景毛玻璃效果选项

### ISSUE THREAD

**Issue by guanzhendong** [iTofu/LCActionSheet#19]
微信的现在有毛玻璃效果

**Comment by iTofu** [comment]
正有此意，有空加。

**Comment by guanzhendong** [comment]
@iTofu 希望尽快加咯

**Comment by iTofu** [comment]
ok，这两天吧。

**Comment by iTofu** [comment]
@guanzhendong 
加上了毛玻璃效果，你可以更新看看：[V 2.2.0](https://github.com/iTofu/LCActionSheet/releases/tag/2.2.0)。

**Comment by guanzhendong** [comment]
@iTofu 恩，知道
