### ISSUE TITLE
Hey 我发现没有以前好用啦 我又倒回到1.2.1啦

### ISSUE THREAD

**Issue by ly918** [iTofu/LCActionSheet#21]
1.2.1可以添加数组，最新版如何传入数组捏？？？

**Comment by ly918** [comment]
Like:

(V Lastest)LCActionSheet \* sheet = [LCActionSheet sheetWithTitle:@"操作" delegate:self cancelButtonTitle:@"取消" otherButtonTitles:?????? nil];

(V 1.2.1)[LCActionSheet sheetWithTitle:@"操作" buttonTitles:_hiddenTool?@[@"保存二维码"]:@[@"保存二维码",@"二维码生成工具"] redButtonIndex:-1 delegate:self];

**Comment by ly918** [comment]
- (void)sheetTest{
  /*
   错误
  
  LCActionSheet \* sheet = [LCActionSheet sheetWithTitle:@"操作" cancelButtonTitle:@"取消" clicked:^(LCActionSheet *actionSheet, NSInteger buttonIndex) {
  
  ```
  NSLog(@"%d",(int)buttonIndex);
  ```
  
  } otherButtonTitles:@[@"Action1",@"Action2",@"Action3"], nil];
  
  [sheet show];
  
  */
  
  LCActionSheet \* sheet = [LCActionSheet sheetWithTitle:@"操作" cancelButtonTitle:@"取消" clicked:^(LCActionSheet *actionSheet, NSInteger buttonIndex) {
  
  ```
  NSLog(@"%d",(int)buttonIndex);
  ```
  
  } otherButtonTitles:@"Action1",@"Action2",@"Action3", nil];
  
  [sheet show];
  }

**Comment by iTofu** [comment]
二楼传的是正确的，现在的版本采取了类似系统 UIActionSheet 的方式传数组参数，多参数传递，用逗号隔开即可。

**Comment by iTofu** [comment]
三楼正确

**Comment by ly918** [comment]
想传个数组指针怎么办

**Comment by iTofu** [comment]
这个不行✋🏻

发自我的 iPhone

**Comment by iTofu** [comment]
@ly918 
现在又可以使用数组初始化了哦~
