### ISSUE TITLE
希望增加单独设置取消按钮颜色的字段

### ISSUE THREAD

**Issue by IAMJ** [iTofu/LCActionSheet#22]
现在有普通按钮、高亮按钮、取消按钮都不同颜色的需求。。

**Comment by iTofu** [comment]
。。。。需求简单，但是跟这个框架貌似不容易怼起来。。。框架内取消按钮是 UIButton，其他按钮都是 Cell。。。这需求太吊了。。。你要不 fork 过去改改，我最近略忙，赶直播 App。。。

**Comment by IAMJ** [comment]
@iTofu 好的。。各种奇葩需求

**Comment by ly918** [comment]
great

**Comment by ly918** [comment]
新版 可以传输组 真是太棒了

**Comment by iTofu** [comment]
@ly918 
都需要那就加上了

**Comment by IAMJ** [comment]
≖‿≖✧ 我自己加上了，另外还可以自定义 bottomView 的背景色

**Comment by iTofu** [comment]
@IAMJ 
Good job！有空可以提个 [pull request](https://github.com/iTofu/LCActionSheet/pulls) :)

**Comment by IAMJ** [comment]
@iTofu 好，等我把奇葩项目这个版本折腾完

**Comment by iTofu** [comment]
ok
