### ISSUE TITLE
点击屏幕空白处，buttonidex返回0

### ISSUE THREAD

**Issue by andforce** [iTofu/LCActionSheet#24]
ActionSheet显示的时候，点击屏幕空白处，buttonidex返回0，不应该触发clicked啊，
1.2.3版本没有问题~

**Comment by iTofu** [comment]
这是为了一起监听空白区域的点击事件，点击空白区域和取消按钮对应的处理方法应该是一致的，所以就强行触发了一波clicked at index 0，方便开发者处理，当然也可以选择不处理。

发自我的 iPhone

**Comment by andforce** [comment]
原来是这样啊，了解
