### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by zscorpio** [iTofu/LCActionSheet#26]
新版本强了很多...不过从v1过来的人表示很忧伤,完全不兼容,全部需要重新写...好尴尬,不清楚当时为什么没有升级上来,也没限制版本.

**Comment by iTofu** [comment]
这个……历史总是在向前发展嘛，产品也会慢慢优化和改进的……
另外一般而言，比如版本号：V a.b.c，b 和 c 的递进一般不会产生向下兼容性变化，而 a 的递进是可能会产生向下兼容的不支持……
如果你确实不想更新，你可以限制下版本，这么设置即可：

``` ruby
pod 'LCActionSheet', '1.0.0' # 1.0.0 可以改成你想要的版本
```

更多限制参考，来自这个博客 —— [wangzz](http://blog.csdn.net/wzzvictory/article/details/19178709)：

``` ruby
pod 'AFNetworking'      #不显式指定依赖库版本，表示每次都获取最新版本  
pod 'AFNetworking', '2.0'     #只使用2.0版本  
pod 'AFNetworking', '> 2.0'     #使用高于2.0的版本  
pod 'AFNetworking', '>= 2.0'     #使用大于或等于2.0的版本  
pod 'AFNetworking', '< 2.0'     #使用小于2.0的版本  
pod 'AFNetworking', '<= 2.0'     #使用小于或等于2.0的版本  
pod 'AFNetworking', '~> 0.1.2'     #使用大于等于0.1.2但小于0.2的版本  
pod 'AFNetworking', '~>0.1'     #使用大于等于0.1但小于1.0的版本  
pod 'AFNetworking', '~>0'     #高于0的版本，写这个限制和什么都不写是一个效果，都表示使用最新版本 
```

**Comment by iTofu** [comment]
以后如果出现向下兼容不支持的情况我尽量写一个 过渡指南……

**Comment by zscorpio** [comment]
恩,是的,之前好像是pod 'Masonry','~>0.6.0'限制了你的版本更新...一直是v1
恩,升级倒是会,就是比较麻烦,我要全部替换哈,然后老版本
LCActionSheet消失,或者点击空白,没有回调,用不了...比较尴尬,不过能够理解产品升级哈哈,新版完美!

**Comment by iTofu** [comment]
谢谢夸奖！好用就好！升级会麻烦一点，不过升完了再用应该会有更舒服的体验！

发自我的 iPhone

**Comment by zscorpio** [comment]
恩,我把调用的地方升级下好了
