### ISSUE TITLE
Unused variable self.backWindow

### ISSUE THREAD

**Issue by xingheng** [iTofu/LCActionSheet#3]
It seems that the backWindow is unused in class LCActionSheet, it that right? or pls explain it briefly. Thanks!

**Comment by iTofu** [comment]
When statusBarStyle is UIStatusBarStyleLightContent, the darkView will not affect the white statusBar. That's it, thanks [chenwei](https://github.com/weiwei1035)'s advise.
[Update Logs with Chinese](https://github.com/LeoiOS/LCActionSheet#更新日志-20150508-update-logs)

**Comment by xingheng** [comment]
OK, my bad. I just found it has setter for self.backWindow without getter in your class, and yes, you don't have to manage the backWindow object in ARC, so it's dealloc after the LCActionSheet is released.
Please close this issue, thanks!

**Comment by iTofu** [comment]
Nothing:)
