### ISSUE TITLE
问题：keyWindow 以及在特定位置插入新的按钮

### ISSUE THREAD

**Issue by cochat** [iTofu/LCActionSheet#34]
能不能支持下多window情况，现在只在keyWindow才能用

**Comment by iTofu** [comment]
请问您这边多 window 的使用场景大致是什么样的？

**Comment by cochat** [comment]
图片预览使用的是window,里面有个长按操作，要弹出来这个选项，期待。。。

**Comment by iTofu** [comment]
能否把图片预览时的 window 设为 keyWindow 呢？按 iOS 系统的一些实现（比如 UIAlertView 的生命周期）来讲，被用户响应的 window 应该被切换成 keyWindow 吧？

**Comment by cochat** [comment]
我没有设置为keyWindow,也能响应事件啊，我先换成keyWindow试试。。。

**Comment by iTofu** [comment]
换吧…… 本来响应的 window 就应该是 keyWindow，其次这些东西按系统做法来肯定是最好的…… 切换 keyWindow 我以前通过 UIAlertView 验证过：

> http://note.leodev.me/2015/12/29/iOS-How-to-implement-the-UIAlertView-of-the-system/

**Comment by cochat** [comment]
好的，还有就是一个，能在任意位置插入buttongTitles吗？

**Comment by iTofu** [comment]
目前只能拼到末尾，任意位置插入需要再提供个方法，你们还有这种需求啊？

**Comment by cochat** [comment]
是的，我们先出来一部分选项，满足条件时，再加入一些到里面，比如识别屏幕上的二维码，就是先出来一部分，等识别完认为是二维码时，在某个位置加入一项

**Comment by iTofu** [comment]
已实现该需求，见 [V 3.1.0](https://github.com/iTofu/LCActionSheet/releases/tag/3.1.0)。

**Comment by iTofu** [comment]
Done.
