### ISSUE TITLE
问题：提供属性：屏幕旋转时 ActionSheet 自动隐藏，默认不自动隐藏

### ISSUE THREAD

**Issue by cochat** [iTofu/LCActionSheet#35]
还有就是能提供一个配置，旋转屏幕自动隐藏掉的功能吗？微信是这样做的

**Comment by iTofu** [comment]
这个需求其实在 UIViewController 中非常容易实现，在 `viewWillLayoutSubviews` 方法中隐藏即可……框架也可以实现，等我手上工作松一点可以考虑加上。
另外微信这样做我不认为是一个 Feature，而是一个解决 Bug 的方案。微信的 ActionSheet 在之前的版本中有一个 Bug，转屏后不会重新渲染布局，比如竖屏下 show，旋转到横屏，ActionSheet 并没有横向拓展，而是占了屏幕左半部分，后面的版本中我发现微信改成了转屏时 hide ActionSheet。
这是一个有趣的事情。

**Comment by iTofu** [comment]
又捕捉到一次……见下图：
![wechatimg74](https://cloud.githubusercontent.com/assets/10044430/25333812/70ad29b0-291e-11e7-856f-d87e391b9ee8.png)

**Comment by cochat** [comment]
厉害！！！

**Comment by iTofu** [comment]
正常的样式应该是这样的：

![wechatimg75](https://cloud.githubusercontent.com/assets/10044430/25334029/6f58294c-291f-11e7-9986-b16fe8ce9585.png)

当然并不是说微信的工程师不会写布局……而是这确实是有 Bug 的，interesting……

**Comment by iTofu** [comment]
所以当前至少我们这个横竖屏不会出 Bug，因为是 AutoLayout…… 不过这个需求我有空加上了再@你吧。

**Comment by cochat** [comment]
好的，多谢。。。

**Comment by iTofu** [comment]
已实现该需求，见 [V 3.1.0](https://github.com/iTofu/LCActionSheet/releases/tag/3.1.0)。

**Comment by iTofu** [comment]
Done.
