### ISSUE TITLE
About iPad 横屏适配问题

### ISSUE THREAD

**Issue by MourinhoLove** [iTofu/LCActionSheet#36]
在 iPad 默认横屏下，依旧是从左边弹出，是否有相关的属性，可以设置从下往上的弹出。

**Comment by iTofu** [comment]
验证问题存在。
目测原因是直接把 ActionSheet 放在 Window 上，而又没有给 Window 一个 rootViewController 导致，稍等修复。

**Comment by iTofu** [comment]
@MourinhoLove 
[V 3.2.1](https://github.com/iTofu/LCActionSheet/releases/tag/3.2.1) 已修复，待更新验证。

**Comment by MourinhoLove** [comment]
@iTofu 验证完成，已经修复
