### ISSUE TITLE
也就是说3.2版本开始status bar就始终只能是黑色了吗？

### ISSUE THREAD

**Issue by luyud** [iTofu/LCActionSheet#38]
我有些页面的status bar是黑色， 有些是白色， 在使用旧版本的时候没有影响，原本是什么颜色就是什么颜色， 但是新版本后变得很尴尬。。白色的状态栏在显示sheet后变成了黑色，点击后又变回白色。。你可能为了多种原因重构了代码， 但是我还是选择旧版本好了。。

**Comment by iTofu** [comment]
你是使用的 `preferredStatusBarStyle` 还是 `[UIApplication sharedApplication].statusBarStyle`？

**Comment by luyud** [comment]
`preferredStatusBarStyle`
在需要显示白色状态栏的地方我调用如下方法
```
- (UIStatusBarStyle)preferredStatusBarStyle {
    return UIStatusBarStyleLightContent;
}
```

**Comment by iTofu** [comment]
好的，已找到该问题，稍后修复。

**Comment by iTofu** [comment]
已修复，[V 3.2.2](https://github.com/iTofu/LCActionSheet/releases/tag/3.2.2)，请更新验证 :)

**Comment by luyud** [comment]
非常感谢

**Comment by iTofu** [comment]
没事，我刚好正百无聊赖，你更新下看看修复情况吧，应该是修好了。

**Comment by luyud** [comment]
😁是的，已经好了，厉害厉害

**Comment by iTofu** [comment]
👌
