### ISSUE TITLE
pod search LCActionSheet 只能搜索到3.2.1版本

### ISSUE THREAD

**Issue by Brances** [iTofu/LCActionSheet#39]

**Comment by iTofu** [comment]
更新时请使用 `pod update` 命令而不是 `pod install` 命令，并且不要带 `--no-repo-update` 后缀。

**Comment by Brances** [comment]
1.因为我的电脑一直pod update 没反应，所以每次我都习惯用pod install.而且podfile中添加LCActionSheet  pod 一直卡着不动~
2.我尝试着直接下载LCActionSheet拖进工程，但是下载下来的文件LCActionSheet，我下载了两次
![image](https://cloud.githubusercontent.com/assets/10275640/26094450/a29e5df6-3a4c-11e7-9c92-47a63404b565.png)

**Comment by iTofu** [comment]
1. 这个貌似没有好的办法，我是工作环境直接 ss，让 git 走 ss 就正常速度了：
  ```
  git config --global http.proxy socks5://127.0.0.1:1080 && git config --global https.proxy socks5://127.0.0.1:1080
  ```

2. 这个是咋回事呢…… 你是不是下载了部分或者咋回事？

**Comment by Brances** [comment]
刚我试着用 pod update --verbose --no-repo-update，也是搜索到3.2.1耶
![image](https://cloud.githubusercontent.com/assets/10275640/26094752/cc110f70-3a4d-11e7-89e7-de1efd7ee0ac.png)
而且我也用的ss
![image](https://cloud.githubusercontent.com/assets/10275640/26094807/f0b0c938-3a4d-11e7-9f79-bfd68ffd772f.png)

**Comment by iTofu** [comment]
`pod update` 没反应是因为该命令会首先更新本地 pod spec，然后更新你的 Podfile 中的依赖库，而国内的网络因为你懂的原因，通常会在更新本地 pod spec 时很卡甚至几个小时。而 `pod install` 会直接根据你安装 CocoaPods 时的 pod spec 直接安装 Podfile 中的库，不执行更新本地 pod spec 的操作，所以一般不会卡。
另外如果你加上 `--no-repo-update` 命令则让 update 操作跳过了更新本地 pod spec，这其实是不合适的，因为你本地的 pod spec 肯定不是最新的 pod spec，如果某些库在你上次更新 pod spec 后更新了，你加上 `--no-repo-update` 后缀则可能不会更新这些库。
你有 ss 环境更好，开启 ss，执行下我上面贴的命令然后再执行 `pod update` 不加任何后缀即可：
```
// 设置让 git 走代理服务
git config --global http.proxy socks5://127.0.0.1:1080 && git config --global https.proxy socks5://127.0.0.1:1080

// 取消设置
git config --global --unset http.proxy && git config --global --unset http.proxy
```

**Comment by Brances** [comment]
好滴，楼主真是太有爱了，这么耐心解答菜鸟的疑问，因为公司的一个APP 用了你的这个库[造物国](https://itunes.apple.com/cn/app/zomake-shop-fancy-designer/id1097474450?l=zh&ls=1&mt=8)，感觉挺不错的，所以新APP准备继续用，刚刚LCActionSheet已经pod下来了，虽然是3.2.1版本，但是并无大碍，我再仔细研究为什么只能pod 3.2.1，因为我的podfile 文件中是从来没有添加过该库的~

**Comment by iTofu** [comment]
没事的，你也不必过于担心这个问题，V 3.2.2 修复的是一个小问题：[ChangeLog](https://github.com/iTofu/LCActionSheet#v-322-20170512)，一般不影响使用。关于版本问题貌似 CocoaPods 那边出现了 Bug，我已经报给他们了等待他们处理：https://github.com/CocoaPods/CocoaPods/issues/6713
另外你们的项目可以放到 [小伙伴](https://github.com/iTofu/LCActionSheet#小伙伴们-partners) 中么？纯收集展示，不会有其他用途。

**Comment by Brances** [comment]
原来是CocoaPods的锅，  哈哈，广告随便打，我可是交不起广告费的哟  （ 渍渍）

**Comment by iTofu** [comment]
完全免费哈哈，就当互相推广吧，再者我这也就是个展示，给你们打广告你们还嫌我这没流量~
不过说句题外话，国民还是版权意识不够啊，诸如 BAT 的项目很多都不带三方协议声明的……

**Comment by iTofu** [comment]
Issue 先 open 着，等这个问题确认完毕我会 @ 你。

**Comment by Brances** [comment]
我们国民版权意识已经在慢慢提高了
哈哈，楼主这么用心必须粉一个。

**Comment by Brances** [comment]
@iTofu  我发现不能获取按钮的标题，就是比如我会检测当前手机APP中是否含有谷歌、高德、百度地图，有则加入到按钮中，所以还要获取到该按钮的标题才能做到此功能，我找了一下好像LCActionSheet对象只有整个视图的title和取消按钮的标题~

**Comment by iTofu** [comment]
是这样，开发者初始化和设置 LCActionSheet 实例时是明确知道它的所有属性的，比如 titles 是开发者传入的，所以开发者应该是能明确知道某个 index 处的 title 的，代理和 Block 方法都会回调 index。

**Comment by Brances** [comment]
好的，明白了，之前没想明白，就用的系统的UIActionSheet。

**Comment by iTofu** [comment]
确定是 CocoaPods 的问题然鹅也没告诉我原因，发了个新版本又好了...

**Comment by Brances** [comment]
@iTofu  辛苦辛苦
