### ISSUE TITLE
actionsheet消失时未将_backWindow.hidden 设置未true

### ISSUE THREAD

**Issue by kuanglijun312** [iTofu/LCActionSheet#4]
如果为了改actionsheet，比如title，在http请求后，更改title,则需要持有actionsheet(即未销毁)，由于新建的Uiwindow；则会锁住界面，就是界面点击无反应；
建议：
- (void)show {
  _backWindow.hidden = NO; //添加hidden 
  [UIView animateWithDuration:0.3f
  ...
  }
- (void)dismiss:(UITapGestureRecognizer *)tap 和 - (void)didClickCancelBtn 在completion:^(BOOL finished) { 添加 _backWindow.hidden = YES;

**Comment by iTofu** [comment]
谢谢，这种情况我没考虑到。
另外，建议在使用时用一次就实例化一个然后show :-)

**Comment by kuanglijun312** [comment]
嗯，谢谢
