### ISSUE TITLE
🐞 状态栏隐藏问题

### ISSUE THREAD

**Issue by devjia** [iTofu/LCActionSheet#42]
看到目前只处理了状态栏style问题 #38 
在隐藏了状态栏的界面弹出sheet的同时出现了状态栏, 应该参考#38 解决一下.

**Comment by devjia** [comment]
或者应该把preferredStatusBarStyle和prefersStatusBarHidden这两个属性暴露出来,让调用者自己去管理状态栏状态.

**Comment by iTofu** [comment]
好的，谢谢提醒。

**Comment by iTofu** [comment]
已经更新了，[V 3.2.3](https://github.com/iTofu/LCActionSheet/releases/tag/3.2.3)。

**Comment by devjia** [comment]
✅  已通过!
非常感谢!

**Comment by iTofu** [comment]
好的。
