### ISSUE TITLE
在iPhoneX上运行，底部的取消是不是要在安全区域啊？

### ISSUE THREAD

**Issue by TML007** [iTofu/LCActionSheet#47]
![snip20171010_1](https://user-images.githubusercontent.com/19261542/31365217-59d20a5a-ad9c-11e7-98c2-71ae73385f8b.png)

**Comment by iTofu** [comment]
emmm... X 的适配规则是啥呢... X...

**Comment by iTofu** [comment]
![emmm](https://user-images.githubusercontent.com/10044430/31367303-f81dc3b8-ad3b-11e7-9caa-514817702b79.jpeg)

**Comment by iTofu** [comment]
已适配：[V 3.3.1](https://github.com/iTofu/LCActionSheet/releases/tag/3.3.1) 。
