### ISSUE TITLE
跳转到横屏页面有问题

### ISSUE THREAD

**Issue by SwiftNie** [iTofu/LCActionSheet#48]
从2.5.2升级到最新版 点击LcactionSheet跳转到下一界面，下一界面的没有横过来，横屏布局变成了竖屏布局

**Comment by iTofu** [comment]
跳转的时候没有 dissmiss LCActionSheet 吗？

**Comment by iTofu** [comment]
跳转的时候没有 dissmiss LCActionSheet 吗？

**Comment by SwiftNie** [comment]
dismiss 不是一般都是库内部操作吗 不需要我门点击每一个按钮都去dismiss一下 并且暴露的方法只有didDismissHandler

**Comment by SwiftNie** [comment]
把跳转语句放在actionSheet?.didDismissHandler block里面就可以了，谢了

**Comment by iTofu** [comment]
应该是 window 导致。

发自我的 iPhone
