### ISSUE TITLE
另外button之间的灰色的线，建议使用backgroundcolor;

### ISSUE THREAD

**Issue by kuanglijun312** [iTofu/LCActionSheet#5]
使用了一次，发现plus上使用cellLine出现未占满的情况；我觉得可以使用uiview，用backgroundcolor来弄；
以上只是建议

**Comment by iTofu** [comment]
这个问题我昨天应该是修复过了，原因是cellLine太短了于是我给他弄成了6000 x 1的尺寸，足以用到iPhone10了:-)
之所以不用UIView + backgroundColor是因为之前在用stroyboard时发现尺寸最小是1个单位，你知道我们开发中使用的尺寸是点单位而非实际像素，因此1个点单位在设备上就是2~3个像素了，它会是一个比较粗的线条……

**Comment by kuanglijun312** [comment]
也对，谢谢
