### ISSUE TITLE
貌似无法单独设置cancle的样式，只能和其他样式一样

### ISSUE THREAD

**Issue by semnyqu** [iTofu/LCActionSheet#50]
貌似无法单独设置cancle的样式，只能和其他样式一样
cancleButtonColor
cancleButtonFont
以及更加灵活的选中点击效果

**Comment by iTofu** [comment]
目前是的，统一设置

**Comment by GPX-NSlog** [comment]
建议可以拎出来单独设置取消按钮颜色

**Comment by iTofu** [comment]
目前有 `NSIndexSet *destructiveButtonIndexSet` 和 `UIColor *destructiveButtonColor` 两个属性来特殊控制警示按钮的文字颜色，可以把 cancel button 的 index 放在 set 中，然后设置 color。
