### ISSUE TITLE
carthage 支持失败

### ISSUE THREAD

**Issue by iOSleep** [iTofu/LCActionSheet#53]
![image](https://user-images.githubusercontent.com/26478957/33538508-aec6d190-d8fc-11e7-9221-415f0444c9e6.png)

**Comment by iTofu** [comment]
一直没怎么用 Carthage，目前的 Carthage 是来自一个 PR，如果导入失败，建议暂时采取 CocoaPods 或 拽入的方式导入。

**Comment by iOSleep** [comment]
那我晚些时候提个pr吧



  
  
  


  
    
      
          
            
              
            
            
              马旭
            
          
            
              
                  邮箱：mx.yolande@gmail.com
              
            
      
    
  


签名由 网易邮箱大师 定制
            在2017年12月04日 14:14，Leo 写道： 一直没怎么用 Carthage，目前的 Carthage 是来自一个 PR，如果导入失败，建议暂时采取 CocoaPods 或 拽入的方式导入。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iTofu/LCActionSheet","title":"iTofu/LCActionSheet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iTofu/LCActionSheet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iTofu in #53: 一直没怎么用 Carthage，目前的 Carthage 是来自一个 PR，如果导入失败，建议暂时采取 CocoaPods 或 拽入的方式导入。"}],"action":{"name":"View Issue","url":"https://github.com/iTofu/LCActionSheet/issues/53#issuecomment-348869577"}}}

**Comment by iTofu** [comment]
可以，非常感谢！

**Comment by iOSleep** [comment]
我看了下，沿用的是之前的pod模板，会改动比较大。

**Comment by iOSleep** [comment]
#54 pr

**Comment by iTofu** [comment]
辛苦了 👍 ，整赶项目稍候 review

**Comment by iTofu** [comment]
@iOSleep 
已 merged，因为有冲突解决，麻烦抽空看下是不是 merged ok 的 :)

**Comment by iTofu** [comment]
主要是 check 下 Carthage 支持

**Comment by iOSleep** [comment]
@iTofu fork打tag测试后，没有发现问题，辛苦了

**Comment by iTofu** [comment]
@iOSleep 
好的辛苦~
