### ISSUE TITLE
发现一严重bug

### ISSUE THREAD

**Issue by CHENDONGY** [iTofu/LCActionSheet#55]
当使用该项目弹出sheet之后。再使用keywindow发生很大的偏移。导致使用你的框架之后，就不能再操作视图的window了

**Comment by lhnoah** [comment]
弹出了sheet之后，keywindow会发生变化。需要sheet消失之后下一个Runloop，keywindow才会变回来

**Comment by iTofu** [comment]
你是说在 actionSheet did dismissed 之前，keyWindow 出现预期外的问题吗？

**Comment by CHENDONGY** [comment]
actionSheet did dismissed 之后，使用MBProgressHUD 弹出在`[UIApplication sharedApplication].keyWindow`上面。发现keywindow的frame发生了变化，x，y不是0了

**Comment by CHENDONGY** [comment]
我下载你提供的demo测试了一下，使用MBProgressHUD弹出再keyWindow上面是正常的。项目中使用的你的项目也是最新版本

**Comment by lhnoah** [comment]
actionSheet did dismissed之前，[UIApplication sharedApplication].keyWindow是ActionSheet的Window

**Comment by lhnoah** [comment]
@CHENDONGY 使用MBProgressHUD可以传入View，你可以传入UIViewController的self.view或者[UIApplication sharedApplication].delegate.window

**Comment by iTofu** [comment]
![emmm](https://user-images.githubusercontent.com/10044430/33592334-6eeb2e44-d9c5-11e7-83b7-5f0c293fd20c.jpeg)
我们应该是没有改动原 keyWindow 的 frame... 如果 demo 表现是正常的，那再核查一下？

**Comment by CHENDONGY** [comment]
我再次确认了一下，在本项目show之前和show之后，前后的keywindow不是一个值了

**Comment by lhnoah** [comment]
当然不是同一个值，ActionSheet使用Window弹出

**Comment by CHENDONGY** [comment]
不过使用demo测试是没有这样的情况 @lhnoah [UIApplication sharedApplication].delegate.window解决了我目前的问题。多谢
