### ISSUE TITLE
请尽快新版本，十万火急

### ISSUE THREAD

**Issue by lhnoah** [iTofu/LCActionSheet#57]
#52 
请针对上面的PR，发一个新版本可以吗？
问题严重，我这边等着上线

**Comment by iTofu** [comment]
抱歉这几天赶项目， #54 还没来得及 review 并且有一些 conflicts 需要处理，计划处理后一块发布新的版本。
#52 已经合并到 master 了，master 是默认分支，你可以让 Pod 直接链接到该分支以获取更新后的代码，应该不影响使用：

```ruby
pod 'LCActionSheet', :git => 'https://github.com/iTofu/LCActionSheet.git'
```

**Comment by lhnoah** [comment]
希望能在CocoaPods官网上正式发一版，我们公司要求只能引CocoaPods上的

公司要求不能直接引GitHub上的库

谢谢！


李航
446798608@qq.com

**Comment by iTofu** [comment]
……这么奇葩，那好吧稍等我发个版本。

**Comment by lhnoah** [comment]
非常感谢～～～


李航
446798608@qq.com

**Comment by iTofu** [comment]
不客气，已经更新了。
