### ISSUE TITLE
ipad 

### ISSUE THREAD

**Issue by lilin87788** [iTofu/LCActionSheet#6]
用在ipad 横屏时会有bug，显示效果不对，action sheet,不是从底部滑出，而是从边上滑出

**Comment by iTofu** [comment]
有空再搞吧，累死了最近。。

**Comment by mrhyh** [comment]
辛苦了，你现在在做什么项目哇，上架了的话给我个名字，我体验下哇！

**Comment by iTofu** [comment]
公司项目还刚起步，不足挂齿~
如果你感兴趣，可以体验体验我的个人项目[『德玛西亚』](https://itunes.apple.com/cn/app/id1067564880)

**Comment by mrhyh** [comment]
好的，谢谢

**Comment by iTofu** [comment]
@lilin87788 
横屏已修复。详见 [V 2.0.0](https://github.com/iTofu/LCActionSheet/releases/tag/2.0.0)。

**Comment by lilin87788** [comment]
谢谢
