### ISSUE TITLE
并没有适配iphoneX

### ISSUE THREAD

**Issue by guoyutao** [iTofu/LCActionSheet#61]

**Comment by iTofu** [comment]
集成的是哪个版本？

**Comment by guoyutao** [comment]
@iTofu 
![image](https://user-images.githubusercontent.com/11513385/34667948-30882796-f4a6-11e7-856c-3df6078160d1.png)

**Comment by iTofu** [comment]
这个版本发布的时候，iPhone X 还没有发布…… 执行 `pod update` 升级到最新版本试试吧……

guoyutao <notifications@github.com>于2018年1月8日 周一下午7:00写道：
