### ISSUE TITLE
pod 报错

### ISSUE THREAD

**Issue by Link-Start** [iTofu/LCActionSheet#68]
[!] Error installing LCActionSheet
[!] /usr/bin/git clone https://github.com/iTofu/LCActionSheet.git /var/folders/jy/kcv5_tdd3zl8779ssc_2l1r40000gn/T/d20181113-43008-wutd4s --template= --single-branch --depth 1 --branch 3.5.0

Cloning into '/var/folders/jy/kcv5_tdd3zl8779ssc_2l1r40000gn/T/d20181113-43008-wutd4s'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by iTofu** [comment]
Git 传输错误，与项目无关。

**Comment by Link-Start** [comment]
不好意思，后来发现是公司网不好!!😅
