### ISSUE TITLE
iphonexs and iphonexMax  screen adaptation

### ISSUE THREAD

**Issue by xiaoweiFive** [iTofu/LCActionSheet#69]
![image](https://user-images.githubusercontent.com/17330916/48484364-e31a9d00-e850-11e8-9100-e2fee8764c07.png)

**Comment by iTofu** [comment]
bad apple ☹️

**Comment by xiaoweiFive** [comment]
😄

**Comment by iTofu** [comment]
[V 3.5.1](https://github.com/iTofu/LCActionSheet/releases/tag/3.5.1)
