### ISSUE TITLE
用clicked的block形式，会与SVProgressHUD冲突

### ISSUE THREAD

**Issue by khalilleo** [iTofu/LCActionSheet#71]
如果在clicked的block里执行[SVProgressHUD show], SVProgressHUD都不会显示，但是使用didDismiss就可以

**Comment by iTofu** [comment]
跟 block 无关。
SVProgressHUD 未指定 view show in keyWindow，LCActionSheet 在 didDismiss 之前 app.keyWindow 都是 LCActionSheet 所在的 window，如果在 didDismiss 之前 show HUD，LCActionSheet dismiss 时会销毁该 window 进而就看不到 HUD，所以你应该在 didDismiss 后 show HUD，或者给 HUD 指定 showed view。
这个逻辑与 LCActionSheet 也无关，系统的指示器也是这个逻辑。参考实践：[系统是怎么实现 UIAlertView 的？](http://note.leodev.me/2015/12/29/iOS-How-to-implement-the-UIAlertView-of-the-system/)

**Comment by khalilleo** [comment]
明白，多谢
